### ISSUE TITLE
"SyntaxError: unexpected token function" on run

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-reconciler#1]
I have NodeJS and Refine installed on a PC running Windows 7 SP1. I successfully installed the reconciler from the command line and then performed an update as suggested by npm (now 5.0.3). When I ran the reconciler on a json dump from the canonical dataset entiteld "p0d.json", however, the following error message appeared:

![firstrun_error_062317](https://user-images.githubusercontent.com/4740995/27479603-2de156b6-57da-11e7-84f4-03682717d47c.JPG)

**Comment by rybesh** [comment]
Sorry about that; you probably need to update the [current](https://nodejs.org/en/download/current/) (not stable) version of node. I am using version 8:
```sh
$ node -v
v8.0.0
```
Anything 8.0.0 or higher should work.

**Comment by rybesh** [comment]
Updated README: https://github.com/periodo/periodo-reconciler/commit/82a90d2a955239de61ec865cf8a8d402399a1611

**Comment by atomrab** [comment]
Works. Close when ready!
