### ISSUE TITLE
Improving reconciliation performance: better recall

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-reconciler#2]
> 1. Not all values that I would expect to bring up partial matches are doing
> so (eg “Jordanian Chalcolithic” in the Perucchetti dataset, or “Possibly
> Archaic” or “Late Republican” in the Met). Also, some direct matches in the
> Europeana spreadsheet didn’t come up (e.g. “vikingatid”). Alo, in the
> Europeana dataset, lots of matches came up for “Hellenistic Period” but none
> at all for “Hellenistic Period (323-31 BC)”.

These are probably due to how I've got the string matching configured; right now I think it is biased toward higher precision and lower recall, which is maybe what we're seeing here. For the ones that you expected to bring up partial matches, can you you give me URLs of some of the definitions you expected to see in the results?

> 2. It is a little inconvenient not to be able to see the spatial coverage
> values until you call up the details window (only the label values appear).
> Then again, for places with two dozen spatial entities attached, seeing all
> of them will be inconvenient. Not sure which wins here.

Yeah, I thought about that too. We could only list the first N characters followed by "…"; would that help?

> 3. Is there a way to match simple to compound names, e.g. “Neolitikum” to
> “tidigneolitikum”,  or “Late Classical” and/or “Hellenistic” to “Late
> Classical--Hellenistic”, or “Third Intermediate” to “name=Third
> Intermediate”? I think we’re likely to get false negatives for a large
> number of labels in Germanic languages where prefixes have been added, and
> we’ll also set the bar higher for aggregators like Europeana, who may not be
> enthusiastic about cleaning up thousands of period label fields from their
> contributors. If we can match strings from the middle of words (e.g.
> *lithikum*), will this make things easier or harder?

We can do that easily. It will increase recall (fewer false negatives) and hurt precision (more false positives). We just need to try it and see where the sweet spot is.

> 4. On a similar note, how should we deal with the common case in which the
> period label expresses a range (e.g. “Late Archaic--Early Classical” or
> “Late Republican--Early Imperial” in the Met dataset) or a set of
> alternatives (“Late Republican or Imperial”) that may or may not be a
> continuous range? Do we simply say you can’t reconcile these with PeriodO? I
> don’t know if it’s possible to do a one-to-many relationship with Refine. I
> suppose you could have two reconciliation columns, include in the second
> only range values, and match the first column to the earliest period and the
> second to the latest. But that does still mean that an expression like “Late
> Archaic--Early Classical” or “Late Archaic or Early Classical” or “Late
> Archaic/Early Classical” or “Late Archaic, Early Classical” would have to
> turn up potential matches including both “Late Archaic” and “Early
> Classical”.

This kind of string manipulation is an area where Refine really shines, so I think that if someone has period labels like this that they are trying to reconcile, the best bet is for them to define two (or more) new derived columns with the alternatives, and then reconcile these derived columns rather than the original labels.

> 5. Can we relax the date parameters so that periods that have a start or end
> (or centerpoint, for that matter) within, say, 100 years of the date-range
> in a spreadsheet still appear as possible matches? This would at least show
> the reconciler that his or her date-range fell outside those of periods with
> the same name and spatial coverage in PeriodO. There were a couple of
> examples here where e.g. the “Villanovan Geometric” period didn’t come up
> with a match because our Villanovan Geometric didn’t overlap (that one ended
> in -800, ours started in -775). But you’re still probably dealing with the
> same concept in this case. Really different concepts with similar labels
> (Woodland Archaic vs Greek Archaic) are likely to be in different places and
> off by a lot more than a century on either side.

Yes, we can do that easily, although again it will increase recall at the cost of precision. Maybe we could add an option when starting up the server that would allow the user to specify whether they want higher precision, or higher recall, which would then affect how we do the matching (both for labels and temporal extents). It could be high-precision by default, and if they had a lot of unmatched labels they could try high-recall.

> 6. Speaking of which, can we add another reconciliation column that also
> looks at period labels? I’m thinking of the frequent column in museum
> databases entitled “culture”, which overlaps in many cases with period
> labels (e.g. “Archaic Greek”). For the Met, for example, this might help get
> more matches, especially for modifiers like “Lydian” that are more likely to
> be reflected in a label than in spatial coverage (e.g.
> http://n2t.net/ark:/99152/p0cmdf9kmfv).

You can reconcile as many columns as you want right now. The reconciliation server doesn't know anything about columns; it just takes as input the data that Refine sends it when you pick a column to reconcile.

> 7. I think some or all of these adjustments will produce a lot more matches.
> But when none of this helps, is there a manual reconciliation process that
> would be somewhere between automated matching and just looking stuff up in
> PeriodO? If your goal is to have a column full of PeriodO URIs, what do you
> do when you have a cell that doesn’t match? Download the csv and fill it in
> by hand?

That's a good question. I'm not sure what the recommended way to do this with Refine is, but I'll look into it.

> 8. Can we make a GREL cookbook or sample scripts to derive columns with URLs
> or date-ranges or start/end dates from the matched PeriodO columns? That is,
> you’re starting with a list of periods, and you reconcile them with PeriodO
> periods, and you want to see the PeriodO date ranges too. There used to be a
> way to extract spatial coordinates from Pleiades URIs in Refine, and it was
> super helpful if you weren’t starting with spatial coordinates that were
> already set. This is more for the student/data novice group, but it might
> help build our audience. I can think of teaching exercises for undergrads
> that would work with this.

Good idea; this is the kind of thing that can go into documentation / resources when we publicize the tool.

> 9. Areas where we’re deficient/will run into trouble: there are some things
> that I noticed across these datasets that I can fix -- gaps in some Greek
> and Roman periods, and language gaps, especially in German (and a bit in
> Danish -- these are evident in the Europeana dataset, so I will try to
> address the former with the German national library). But there’s a bigger
> issue for spatial matching, which is the coverage labels referring to
> historical spatial entities rather than present ones. Museums in particular
> will tend to use modern nations when they talk about provenance, for reasons
> related to their recordkeeping; so if we try to reconcile with space as a
> factor and have only “Roman Empire” for the spatial coverage of “Late
> Republican”, we’re out of luck. Does this mean that we should try to parse
> these in terms of modern nations now? Or should we wait to see if we can
> link to a URI for a historical polygon in, say, Wikidata, and then establish
> the modern countries involved through Allen operators?

I think we want to move toward using polygons rather than place names to do spatial matching. The code that Bits Coop is writing for us will be usable in the reconciliation server for this purpose.

**Comment by rybesh** [comment]
Files from Adam.

[CTPeriodsCyprus.xlsx](https://github.com/periodo/periodo-reconciler/files/1133379/CTPeriodsCyprus.xlsx)

[perucchetti_unicode_betterdateformat.xlsx](https://github.com/periodo/periodo-reconciler/files/1133380/perucchetti_unicode_betterdateformat.xlsx)

[europeana_reconciliation_export.xlsx](https://github.com/periodo/periodo-reconciler/files/1133382/europeana_reconciliation_export.xlsx)

**Comment by atomrab** [comment]
I will continue the thread here, rather than by email. 

>These are probably due to how I've got the string matching configured; right now I think it is biased 
>toward higher precision and lower recall, which is maybe what we're seeing here. For the ones that you 
>expected to bring up partial matches, can you you give me URLs of some of the definitions 
> you expected to see in the results?

I checked the direct matches, and they all turned out to be in the form "Vikingatid (600-1000 AD)", with a following date-range in parentheses (just like the Hellenistic examples). So it's the subsequent parenthesis that seems to block the match (it wasn't just scored low, it didn't appear at all). As for the partial matches I expected, I had "Jordanian Chalcolithic" in "Jordan" and expected to get a hit from e.g. http://n2t.net/ark:/99152/p0m63nj29k7, but got no matches at all.

>We could only list the first N characters followed by "…"; would that help?

Yes, let's do that.

>This kind of string manipulation is an area where Refine really shines, so I think that if someone has
>period labels like this that they are trying to reconcile, the best bet is for them to define two (or more) 
>new derived columns with the alternatives, and then reconcile these derived columns rather than the 
>original labels.

That makes sense. Let's lay that out in the cookbook -- it's not quite at the level of the formal instructions, but could help the novice.

>Yes, we can do that easily, although again it will increase recall at the cost of precision. Maybe we could 
>add an option when starting up the server that would allow the user to specify whether they want 
>higher precision, or higher recall, which would then affect how we do the matching (both for labels and 
>temporal extents). It could be high-precision by default, and if they had a lot of unmatched labels they 
>could try high-recall.

I like the idea of user choice here -- could we make this a set of options ("include incomplete string matches", for example) that would allow the user to participate in hitting that mythical sweet spot between false negatives and false positives?

>You can reconcile as many columns as you want right now. The reconciliation server doesn't know 
>anything about columns; it just takes as input the data that Refine sends it when you pick a column to 
>reconcile.

I expressed this badly. What I meant to suggest is adding a "Secondary Period Label" option to the drop-down list ("Year or Start Year", "End Year", "Spatial Coverage") that appears in the reconciler window when you're adding additional columns for the reconciler to consider. That is, you'd be reconciling against both a primary and a secondary period label column, where the terms in the second column should also be considered for matches against period labels (so you have "Lydian" in a culture column and "Archaic" in a period name column, and get back both http://n2t.net/ark:/99152/p09xsbnfxsx and http://n2t.net/ark:/99152/p0cmdf9kmfv). If this is relatively straightforward on the programming side, it seems like a better solution than merging separate "culture" and "period" columns, since that would give you a lot of extra noise in the results. If you think you'd get better results by reconciling the culture and period columns separately and just picking the value you prefer, though, that's fine too -- we should just suggest that method in the cookbook. I don't have a sense of which method will produce better results (or if they'd be identical).

Everything else sounds good! I've been sending around the reconciler address to people who are dealing with their own period lists, so we may also get some external feedback soon.

**Comment by rybesh** [comment]
I just merged https://github.com/periodo/periodo-reconciler/pull/10, which makes a number of changes to improve recall, most notable by using a Boolean OR to match tokens in a label rather than Boolean AND.

> 1. Not all values that I would expect to bring up partial matches are doing
> so (eg “Jordanian Chalcolithic” in the Perucchetti dataset or “Possibly Archaic”
> or “Late Republican” in the Met).

With the more recall-oriented strategy, these now return reasonable results.

> Also, some direct matches in the
> Europeana spreadsheet didn’t come up (e.g. “vikingatid”).

This word is spelled 'Vikingatid' in PeriodO. In Europeana there seem to be variations 'Vikingetid' and 'Vikingtid'. Should we add alternate labels to the PeriodO record?

> Europeana dataset, lots of matches came up for “Hellenistic Period” but none
> at all for “Hellenistic Period (323-31 BC)”.

This now returns a ton of results, basically anything with 'Hellenistic' in any of its labels.

> 3. Is there a way to match simple to compound names, e.g. “Neolitikum” to
> “tidigneolitikum”,  or “Late Classical” and/or “Hellenistic” to “Late
> Classical--Hellenistic”, or “Third Intermediate” to “name=Third
> Intermediate”?

The latter two work now, but not the first one. Given the way labels are indexed now, it is easy to match at the beginning of a word (i.e. we can make it so that 'Classic' will match 'Classical') but not at the end a word. Fixing this would require writing our own text indexing logic, which is not out of the question if we decide it is necessary.

> 5. Can we relax the date parameters so that periods that have a start or end
> (or centerpoint, for that matter) within, say, 100 years of the date-range
> in a spreadsheet still appear as possible matches?

OK, now anything within 100 years of a period interval will match (but with a lower score than if it had "really" matched).

> 8. Can we make a GREL cookbook or sample scripts to derive columns with URLs
> or date-ranges or start/end dates from the matched PeriodO columns?

Best way to do this would be to support the new Data Extension API: https://github.com/OpenRefine/OpenRefine/wiki/Data-Extension-API

I've added an issue.

**Comment by atomrab** [comment]
> Also, some direct matches in the
> Europeana spreadsheet didn’t come up (e.g. “vikingatid”).
> 
> This word is spelled 'Vikingatid' in PeriodO. In Europeana there seem to be variations 'Vikingetid' and 'Vikingtid'. Should we add alternate labels to the PeriodO record?

Actually, I just checked the dataset, and the problem was with the presence of a parenthetical date statement after the word. That is, they have a "vikingatid" too, but it's in the form "vikingatid (800   e.Kr. - 1100 e.Kr.)". The latest version should have fixed this.
