### ISSUE TITLE
Better control of pop-up window with period details

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-reconciler#6]
The pop-up screen with the period definition details appears in a way that's visible when the value is at the very top or the very bottom of the page, but when the value is near the top or in the upper part of the middle, the pop-up appears partially cut off by the upper bound of the reconciler window. Often you can't scroll down or up far enough to get the window not to be cut off for these values. Is there way we can always make it appear in the middle of the screen so that it's not cut off?

**Comment by rybesh** [comment]
Unfortunately the placement of this window is controlled by OpenRefine, so there is no way to do this except to patch OpenRefine.
