### ISSUE TITLE
Sensitivity of string matching

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-reconciler#8]
I know this is already on the list, but just in case the period is a different issue, the PeriodO label "Athenian supremacy, 479-431 B.C" without the final period in "B.C." (stripped in the LCSH LD interface) won't match against "Athenian supremacy, 479-431 B.C." with the final period.

**Comment by rybesh** [comment]
Fixed by https://github.com/periodo/periodo-reconciler/pull/10
